env:
  es6: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
parser: 'babel-eslint'
extends: alchemy
settings:
  import/resolver:
    webpack:
      config: './config/webpack.config.eslint.js'
plugins:
  - react
  - jsx-a11y
  - import
rules:
  no-console:
    - error
    - 'allow':
      - 'warn'
      - 'error'
      - 'info'
  import/no-extraneous-dependencies: 0
