sudo: required

language: node_js

node_js:
  - 8
  - 9

cache:
  npm: true
  directories:
     - node_modules

install:
  - yarn install

script:
  - node --version
  - npm test
  - npm run build:all
  - npm run packager:linux
  - npm run packager:linux:deb
